apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: gomjanr1y-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/gomjanr1y-java-quarkus-gitops